Merge rgi data manager and wrapper
arpcard/rgi_wrapper pull request #2
Opened 2018-12-19 22:24 UTC by mjram0s

2018-12-21 15:29 UTC, apetkau commented
Thanks @mjram0s. I am in the process of testing this out :smile:

2019-01-02 17:53 UTC, apetkau requested changes
Thanks for adding this @mjram0s, it looks awesome :smile:. I have a few comments listed below, but everything worked for me when I installed RGI and the database builder.

2019-01-02 17:53 UTC, apetkau commented on data_managers/data_manager_rgi_build_db/data_manager/rgi_database_builder.py
> +#version = _main(args)
Instead of leaving code commented out, could you delete it (it can always be recovered again using git)?

2019-01-02 17:53 UTC, apetkau commented on data_managers/data_manager_rgi_build_db/tool-data/rgi_databases.loc.sample
> +#apiMel3	apiMel3	Honeybee (Apis mellifera): apiMel3		/path/to/genome/apiMel3/apiMel3.fa
Could this file be changed so that the examples listed here correspond to the RGI databases?  For example:

```
rgi_20181001    rgi_20181001    /galaxy-central/tool-data/rgi_databases/rgi_20181001
```

All references to the human genome databases can be removed (pretty much all text in this file).

2019-01-02 17:53 UTC, apetkau commented on data_managers/.shed.yml
> +categories:
I do not believe you need the `data_managers/.shed.yml` file since there already exists the main `.shed.yml` file and both the main RGI tool and the database manager will be uploaded to the same repository.

2019-01-02 17:53 UTC, apetkau commented on data_managers/data_manager_conf.xml
> +                        <!--<source>${path}</source> -->
Could you remove this commented-out value in the XML file?

2019-01-02 17:53 UTC, apetkau commented on data_managers/data_manager_rgi_build_db/data_manager/rgi_database_builder.xml
> +    <description>database builder</description>
Could this be changed to something more descriptive like **RGI database  builder**?

2019-01-02 17:53 UTC, apetkau commented on data_managers/data_manager_rgi_build_db/data_manager/rgi_database_builder.xml
> +        <param name="url" type="text" value="" label="Url" help="Url for the CARD data e.g https://card.mcmaster.ca/download/0/broadstreet-v3.0.0.tar.gz" optional="True"/>
I believe if you set something like `value="https://card.mcmaster.ca/latest/data"` then this parameter will default to this value (which should be the latest database).

In the **help** section could you also link to https://card.mcmaster.ca/download which is where someone would go to search for previous CARD releases.

2019-01-02 17:53 UTC, apetkau commented on data_managers/data_manager_rgi_build_db/data_manager/import_data.py
> +"""
Could you remove this commented out section of code?

2019-01-03 14:56 UTC, raphenya commented
@mjram0s Is it possible to migrate the `rgi_database_builder.py` and `import_data.py` to python 3?

2019-01-03 20:00 UTC, mjram0s commented
@raphenya Yes, I will look into it tomorrow!

2019-01-03 21:30 UTC, apetkau commented
Thanks @mjram0s, everything's working for me. Just the one request from @raphenya and that should be it :smile:

2019-01-08 19:58 UTC, raphenya reviewed
maybe for constructing paths you can use `os.path.join` and also use `format` for strings

2019-01-10 22:29 UTC, apetkau commented on data_managers/data_manager_rgi_build_db/data_manager/rgi_database_builder.xml
> +        <requirement type="package" version="4.2.2">rgi</requirement>
I get the error 

```
Fatal error: Exit code 1 (Error)
Traceback (most recent call last):
  File "/home/aaron/software/shed_tools/jupiter.cscscience.ca/repos/admin/rgi/feea0bca16b1/rgi/data_managers/data_manager_rgi_build_db/data_manager/rgi_database_builder.py", line 8, in <module>
    import urllib.request, urllib.error, urllib.parse
ImportError: No module named request
```

I think you need to add whatever package has `urllib.request` that's available in conda to the requirements.

2019-01-10 23:28 UTC, apetkau commented on data_managers/data_manager_rgi_build_db/data_manager/rgi_database_builder.xml
> +        <requirement type="package" version="4.2.2">rgi</requirement>
I actually wonder if you need to specify a specific version of `python` since for me, the tool seems to be still running with Python 2 (and so giving the above errors)? This could just be a mistake on how I set it up though.

2019-01-14 20:39 UTC, mjram0s commented on data_managers/data_manager_rgi_build_db/data_manager/rgi_database_builder.xml
> +        <requirement type="package" version="4.2.2">rgi</requirement>
Fixed by indicating python3 as the interpreter in the data manager xml file.

2019-01-16 14:55 UTC, raphenya requested changes
@mjram0s Import or Update `writeFASTAfromJson` function, see a newer function (`write_fasta_from_json`) that uses bit-scores in this file https://github.com/arpcard/rgi/blob/master/app/Database.py

I think importing will be ideal, so that we have one place to change the code.

2019-01-18 20:45 UTC, apetkau commented
Thanks for all the updates @mjram0s. Using the default database that comes with rgi in bioconda works great. And the tests work.

2019-01-21 19:38 UTC, raphenya approved these changes

2019-01-21 21:00 UTC, merged

2019-01-22 19:08 UTC, apetkau commented
Thanks @raphenya